widgets:
    -
        type: recent_posts
        position: left
    -
        type: categories
        position: left

    -
        # Where should the widget be placed, left sidebar or right sidebar
        type: toc
        # Whether to show the index of each heading
        position: right
        index: true
        # Whether to collapse sub-headings when they are out-of-view
        collapsed: true
        # Maximum level of headings to show (1-6)
        depth: 3
    # Recommendati
    -
        type: tags
        position: right
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true